#!/usr/bin/env python3

import sys

from helpers import *
from analyzer import Analyzer
from termcolor import colored


def main():
	# ensure proper usage
	if len(sys.argv) != 2:
		sys.exit("Usage: ./tweets @screen_name(without @)")

	username = sys.argv[1]

	# Get 50 most recent tweets
	tweets = get_user_timeline(username, 50)

	# Handle the case when no tweets are fetched.
	if tweets is None:
		return

	# instantiate analyzer
	analyzer = Analyzer()

	# Print all tweets according to score
	for tweet in tweets:
		score = analyzer.analyze(tweet)
		if score > 0:
			print(colored(tweet + " - " + str(score), color="green"))
		elif score < 0:
			print(colored(tweet + " - " + str(score), color="red"))
		else:
			print(colored(tweet + " - " + str(score), color="yellow"))

if __name__ == '__main__':
	main()
